# @package _global_

# specify here default training configuration
defaults:
    - models: dino #supervised, dino
    - datamodules: inat2021_52 #inat2021_52
    - experiments: default #default

    - override  hydra/job_logging: disabled 
    - override  hydra/hydra_logging: disabled
hydra:
    run:
        dir: .
    output_subdir: null 

